import type { BoardSnapshot } from "@/lib/types";
import type { BoardState } from "./store";
import { animationFrame } from "./animation";

type TutorItem = { id: string; text: string; status: "visible" | "entering"; kinds: string[] };

export type LiveBoard = BoardSnapshot & {
  open?: boolean;
  revision?: number;
  tutorItems?: TutorItem[];
  studentStrokeCount?: number;
  studentImageUrl?: string;
};

export function boardProvenance(state: BoardState) {
  const visibleAnimation = new Set(state.animation ? animationFrame(state.animation, state.time).groups.filter(group => group.opacity > 0).map(group => group.id) : []);
  return {
    revision: state.revision,
    studentStrokeCount: state.student.length,
    tutorItems: [
      ...state.groups.map(group => ({
        id: group.id,
        text: group.drawables.flatMap(mark => mark.kind === "text" ? [mark.text] : []).join(" "),
        status: group.appear === "done" ? "visible" as const : "entering" as const,
        kinds: [...new Set(group.drawables.map(mark => mark.kind))],
      })),
      ...(state.animation ? state.animation.shapes.map(shape => ({ id: shape.id, text: "text" in shape ? shape.text : "label" in shape ? shape.label ?? "" : "", status: visibleAnimation.has(shape.id) ? "visible" as const : "entering" as const, kinds: [`animation:${shape.kind}`] })) : []),
    ],
  };
}

export function describeBoard(board: LiveBoard | null) {
  return `\n<board_ownership>The board is live app state, not a student submission. Tutor items below were generated by YOU, including automatic writing from your speech. Never attribute them to the student or diagnose the student's reasoning from them. If they are stale or wrong, own the error and update them. Only the separate student-ink image is student work. No student ink means the student has written nothing on the board. An entering item is already accepted and still being revealed; do not mistake an incomplete image for a student omission. Judge the student's words and their own ink only. If provenance is unavailable, authorship is unknown, not student-authored. Reuse the listed IDs to update your notes; remove stale tutor items. When moving to a new phase, write the new topic FIRST, then rewrite the equation and current givens. Changing the reserved topic ID starts a fresh tutor note, preserving student ink. DRAW clear also clears only tutor content. Do not change only the heading and leave old quantities.\n${JSON.stringify({ revision: board?.revision ?? null, studentStrokeCount: board?.studentStrokeCount ?? null, tutorItems: board?.tutorItems ?? [] })}\n</board_ownership>`;
}

let live: LiveBoard | null = null;
let snapshotProvider: (() => LiveBoard | null) | null = null;

export function setBoardSnapshotProvider(provider: (() => LiveBoard | null) | null) {
  snapshotProvider = provider;
}

export function setLiveBoard(next: LiveBoard | null) {
  live = next;
}

export function getLiveBoard(): LiveBoard | null {
  return snapshotProvider ? snapshotProvider() : live;
}

export function asLiveBoard(value: unknown): LiveBoard | null {
  if (!value || typeof value !== "object") return null;
  const board = value as Partial<LiveBoard>;
  const open = board.open === true;
  const imageUrl = typeof board.imageUrl === "string" ? board.imageUrl : "";
  const studentShapesSince =
    typeof board.studentShapesSince === "string" ? board.studentShapesSince : "";
  if (!open && !imageUrl && !Array.isArray(board.tutorItems)) return null;
  const tutorItems = Array.isArray(board.tutorItems) ? board.tutorItems.slice(0, 100).flatMap(item =>
    item && typeof item.id === "string" && typeof item.text === "string" ? [{
      id: item.id.slice(0, 100), text: item.text.slice(0, 500),
      status: item.status === "entering" ? "entering" as const : "visible" as const,
      kinds: Array.isArray(item.kinds) ? item.kinds.filter(kind => typeof kind === "string").slice(0, 8) : [],
    }] : []
  ) : undefined;
  return { imageUrl, studentShapesSince, open, tutorItems,
    revision: Number.isSafeInteger(board.revision) ? board.revision : undefined,
    studentStrokeCount: Number.isSafeInteger(board.studentStrokeCount) && board.studentStrokeCount! >= 0 ? board.studentStrokeCount : undefined,
    studentImageUrl: typeof board.studentImageUrl === "string" ? board.studentImageUrl : undefined,
  };
}
