import type { AnimationSpec, BoardSnapshot } from "@/lib/types";
import type { BoardState } from "./store";
import { animationFrame, validateAnimation } from "./animation";

type TutorItem = { id: string; text: string; status: "visible" | "entering" | "unresolved"; kinds: string[]; layout?: string };

export type LiveBoard = BoardSnapshot & {
  open?: boolean;
  revision?: number;
  tutorItems?: TutorItem[];
  studentStrokeCount?: number;
  studentImageUrl?: string;
  page?: number;
  earlierPages?: { page: number; topic: string }[];
  readingEarlier?: boolean;
  animation?: { spec: AnimationSpec; time: number; playing: boolean };
};

export function boardProvenance(state: BoardState) {
  const visibleAnimation = new Set(state.animation ? animationFrame(state.animation, state.time).groups.filter(group => group.opacity > 0).map(group => group.id) : []);
  return {
    revision: state.revision,
    animation: state.animation ? { spec: state.animation, time: state.time, playing: state.playing } : undefined,
    page: state.pageId,
    earlierPages: state.earlierPages.map(page => ({ page: page.id, topic: page.groups.find(group => group.id === 'topic')?.drawables.flatMap(mark => mark.kind === 'text' ? [mark.text] : []).join(' ') ?? 'Earlier notes' })),
    studentStrokeCount: state.student.length,
    tutorItems: [
      ...state.groups.map(group => ({
        id: group.id,
        text: group.drawables.flatMap(mark => mark.kind === "text" ? [mark.text] : []).join(" "),
        status: group.unresolved ? 'unresolved' as const : group.appear === "done" ? "visible" as const : "entering" as const,
        layout: group.source ? JSON.stringify(group.source).slice(0, 1200) : undefined,
        kinds: [...new Set(group.drawables.map(mark => mark.kind))],
      })),
      ...(state.animation ? state.animation.shapes.map(shape => ({ id: shape.id, text: "text" in shape ? shape.text : "label" in shape ? shape.label ?? "" : "", status: visibleAnimation.has(shape.id) ? "visible" as const : "entering" as const, kinds: [`animation:${shape.kind}`] })) : []),
    ],
  };
}

export function describeBoard(board: LiveBoard | null) {
  return `\n<board_ownership>The board is live app state, not a student submission. Tutor items below were generated by YOU, including typeset equations and generated diagrams. Never attribute them to the student or diagnose the student's reasoning from them. If they are stale or wrong, own the error and update them. Only the separate student-ink image is student work. No student ink means the student has written nothing on the current working page; earlier pages may still contain their work. An entering item is already accepted and still being revealed; do not mistake an incomplete image for a student omission. Judge the student's words and their own ink only. If provenance is unavailable, authorship is unknown, not student-authored. The animation field contains your current scene, playback position, and playing state. Resume or focus it using those IDs instead of reconstructing it from the image. Reuse an animation scene ID to revise it on this page, retaining all shapes that should remain. To animate a static object in place, reuse its exact ID in the animation; the background and student ink stay on the page. Use a new scene ID for a separate illustration. Reuse the listed IDs to update your notes; remove stale tutor items. When moving to a new phase, write the new topic FIRST, then write only the established givens or relationships permitted by the current teaching move. Changing the reserved topic ID continues on a fresh working page below the earlier notes. Earlier pages, including student ink, remain in the scrollback. A full writing page also continues automatically. The supplied image and item IDs describe the current working page only; earlier pages are read-only history. If readingEarlier is true, the student has scrolled back, so do not claim the new working page is in view. Do not confuse earlier topic summaries with current givens. DRAW clear also clears only tutor content. Do not change only the heading and leave old quantities.\n${JSON.stringify({ page: board?.page ?? 1, earlierPages: board?.earlierPages ?? [], readingEarlier: board?.readingEarlier ?? false, revision: board?.revision ?? null, studentStrokeCount: board?.studentStrokeCount ?? null, animation: board?.animation ?? null, tutorItems: board?.tutorItems ?? [] })}\n</board_ownership>`;
}

let live: LiveBoard | null = null;
let snapshotProvider: (() => LiveBoard | null) | null = null;

export function setBoardSnapshotProvider(provider: (() => LiveBoard | null) | null) {
  snapshotProvider = provider;
}

export function setLiveBoard(next: LiveBoard | null) {
  live = next;
}

export function getLiveBoard(): LiveBoard | null {
  return snapshotProvider ? snapshotProvider() : live;
}

// Desk entry changes the store before React mounts its snapshot provider. The
// first spoken request must still carry that board's availability/authorship.
export function boardContextForTurn(state: BoardState): LiveBoard | null {
  return getLiveBoard() ?? (state.open ? {
    ...boardProvenance(state), open: true, imageUrl: '', studentShapesSince: state.studentSince,
  } : null);
}

export function asLiveBoard(value: unknown): LiveBoard | null {
  if (!value || typeof value !== "object") return null;
  const board = value as Partial<LiveBoard>;
  const open = board.open === true;
  const imageUrl = typeof board.imageUrl === "string" ? board.imageUrl : "";
  const studentShapesSince =
    typeof board.studentShapesSince === "string" ? board.studentShapesSince : "";
  if (!open && !imageUrl && !Array.isArray(board.tutorItems)) return null;
  const tutorItems = Array.isArray(board.tutorItems) ? board.tutorItems.slice(0, 100).flatMap(item =>
    item && typeof item.id === "string" && typeof item.text === "string" ? [{
      id: item.id.slice(0, 100), text: item.text.slice(0, 500),
      status: item.status === 'unresolved' ? 'unresolved' as const : item.status === "entering" ? "entering" as const : "visible" as const,
      layout: typeof item.layout === 'string' ? item.layout.slice(0, 1200) : undefined,
      kinds: Array.isArray(item.kinds) ? item.kinds.filter(kind => typeof kind === "string").slice(0, 8) : [],
    }] : []
  ) : undefined;
  const spec = validateAnimation(board.animation?.spec);
  return { imageUrl, studentShapesSince, open, tutorItems,
    animation: spec ? { spec, time: Math.max(0, Math.min(spec.duration, Number(board.animation?.time) || 0)), playing: board.animation?.playing === true } : undefined,
    page: Number.isSafeInteger(board.page) && board.page! > 0 ? board.page : undefined,
    earlierPages: Array.isArray(board.earlierPages) ? board.earlierPages.slice(-100).flatMap(page => page && Number.isSafeInteger(page.page) && typeof page.topic === 'string' ? [{ page: page.page, topic: page.topic.slice(0, 100) }] : []) : undefined,
    readingEarlier: board.readingEarlier === true,
    revision: Number.isSafeInteger(board.revision) ? board.revision : undefined,
    studentStrokeCount: Number.isSafeInteger(board.studentStrokeCount) && board.studentStrokeCount! >= 0 ? board.studentStrokeCount : undefined,
    studentImageUrl: typeof board.studentImageUrl === "string" ? board.studentImageUrl : undefined,
  };
}
