import { createRequire } from 'node:module';
const external = createRequire(import.meta.url);
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import ts from 'typescript';
const cache = new Map();
function load(file) {
  if(cache.has(file))return cache.get(file);
  const loadedModule={exports:{}};
  const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
  vm.runInThisContext(`(function(require,module,exports){${code}\n})`,{filename:file})(name=>name.startsWith('@mathjax/') ? external(name) : load((name.startsWith('@/')?path.resolve(name.slice(2)):path.resolve(path.dirname(file),name))+'.ts'),loadedModule,loadedModule.exports);
  cache.set(file,loadedModule.exports);return loadedModule.exports;
}
const {hitInk,inkPath,moveInk,inkBounds}=load('lib/whiteboard/ink-path.ts');
const points=[{x:.1,y:.2},{x:.9,y:.2}];
assert.ok(hitInk(points,{x:.5,y:.2},{x:.02,y:.01}),'Hit the middle of a sparsely sampled stroke');
assert.ok(!hitInk(points,{x:.5,y:.23},{x:.02,y:.01}),'Respect page aspect ratio and visible eraser radius');
assert.ok(inkPath([{x:.2,y:.3}]).startsWith('M.2,.3') || inkPath([{x:.2,y:.3}]).startsWith('M0.2,0.3'),'A tap produces a dot');
assert.match(inkPath([{x:.1,y:.2},{x:.2,y:.3},{x:.4,y:.2}]),/Q.*L0.4,0.2$/,'Smooth joins preserve endpoints');
const stroke={id:'own',tool:'pen',color:'blue',points};
const other={...stroke,id:'other',points:[{x:.3,y:.5},{x:.4,y:.5}]};
const moved=moveInk([stroke,other],['own'],{x:.4,y:-.4});
assert.equal(moved[1],other,'Unselected ink is untouched');
assert.ok(Math.abs(moved[0].points[1].x-moved[0].points[0].x-.8)<1e-8,'Moving near an edge preserves shape rather than clipping points');
assert.ok(inkBounds(moved[0].points).y>=0 && inkBounds(moved[0].points).x+inkBounds(moved[0].points).w<=1);
const store=load('lib/whiteboard/store.ts');
store.addStudentStroke(stroke);
store.setStudentStrokes(moved);
store.applyDrawCommands([{op:'text',id:'topic',at:{x:.5,y:.12},text:'A new tutor note'}]);
const tutor=structuredClone(store.getBoardState().groups);
store.undoStudentInk();
assert.deepEqual(store.getBoardState().student,[stroke]);
assert.deepEqual(store.getBoardState().groups,tutor,'Undo your ink cannot revert a newer tutor note');
store.redoStudentInk();assert.deepEqual(store.getBoardState().student,moved);
const parked=structuredClone(store.getBoardState());
store.resetBoard();assert.equal(store.getBoardState().studentPast.length,0);
store.restoreBoard(parked);store.undoStudentInk();assert.deepEqual(store.getBoardState().student,[stroke],'History survives a board view/session restore');
store.addStudentStroke(other);assert.equal(store.getBoardState().studentFuture.length,0,'New work invalidates old redo');
store.eraseStudentStrokes(['own','other']);assert.equal(store.getBoardState().student.length,0);
store.undoStudentInk();assert.equal(store.getBoardState().student.length,2,'One eraser gesture can be undone together');
for(let i=0;i<35;i++)store.addStudentStroke({...stroke,id:String(i)});
assert.equal(store.getBoardState().studentPast.length,30,'History stays bounded');
console.log('PASS: smooth paths, tap dots, segment erasing, aspect-aware hit tests, constrained movement, author-isolated undo/redo, session restore, and bounded ink history.');

const {textReveal,groupReveal}=load('lib/whiteboard/reveal.ts');
const reveal=textReveal('a + Δy');
assert.equal(reveal.glyphs.join(''),'a + Δy');
assert.equal(textReveal('e\u0301').glyphs.length,1,'Combining characters reveal together');
assert.ok(reveal.delays.every((delay,index)=>!index || delay>reveal.delays[index-1]));
const multi={id:'lines',drawables:[{kind:'text',text:'First line'},{kind:'text',text:'Next line'}]};
assert.ok(groupReveal(multi).delays[1]>=textReveal('First line').duration,'Wrapped lines write sequentially');
store.resetBoard();
store.addStudentStroke({id:'page-one-ink',tool:'pen',color:'blue',points:[{x:0,y:0},{x:1,y:1}]});
store.applyDrawCommands([{op:'text',id:'new-line',at:{x:.5,y:.3},text:'F = ma'}]);
assert.equal(store.getBoardState().pageId,2,'Full writing area creates a continuation page');
assert.equal(store.getBoardState().earlierPages[0].student[0].id,'page-one-ink');
assert.equal(store.getBoardState().groups[0].id,'new-line','Writing is retained rather than rejected');
store.addStudentStroke(stroke);store.undoStudentInk();
assert.equal(store.getBoardState().earlierPages[0].student.length,1,'Current undo never alters earlier pages');
const notebook=structuredClone(store.getBoardState());store.resetBoard();store.restoreBoard(notebook);
assert.deepEqual(store.getBoardState().earlierPages,notebook.earlierPages,'All pages survive desk restoration');
console.log('PASS: progressive grapheme timing, sequential lines, overflow continuation, preserved earlier ink, page restoration, and contingent setup-diagram repair.');
