export const DIAGRAM_GUIDANCE = `<diagram_composition>
Make each figure explain one relationship. Choose the visual from the learner's need, not a phrase or topic lookup. Before drawing, decide what is an object, a support/path, an active vector, and a reference. Show only quantities already established or permitted by the teaching move. If asking for a direction, leave that arrow absent until the learner predicts it. Do not add a force diagram, component decomposition, or equation just because the tools can draw one.
Compose the useful scene in x=.12..88, y=.24..70 beneath a short topic heading; leave lower space for the learner. Keep related parts close. Prefer one connected, legible figure over a long line spanning the page, a tiny object, and floating arrows. Object radius around .035..055 is often readable. Use concise attached labels, not sentences. Separate two states spatially only when comparison is the teaching point. Never draw false precision or an unsupported physical relationship.
DRAW accepts optional local diagram metadata with these exact fields:
- fill: "paper" or "tint" for a circle or closed curve. Use tint to distinguish a physical body or a diagram node; leave emphasis circles unfilled.
- weight: "light", "normal", or "strong". Structure/support is ink and strong; active vectors use accent; construction/reference lines are muted and light. Use dashed lines for construction, not a solid physical surface.
- surface: "left" or "right" on a LINE adds short support hatching on that side. Left/right mean the side seen looking from the line's from point toward its to point (on the screen). Hatch inside the solid support, opposite the object.
- contact: {with:"existing-line-id",t:0.4,side:"left"} on a CIRCLE puts its outline exactly tangent to that line at the fraction t from start to end. Supply center and r normally; contact resolves center from the support. Use this for an explicitly understood object resting on a straight surface rather than estimating its center. t must be 0..1; choose the correct side. This is a geometric constraint, not a physics simulation.
- attach: {to:"existing-shape-id",anchor:"center",offset:{x:0,y:0}} on an ARROW or LINE translates its start to the named anchor while preserving its from-to vector. Circle supports center; line/arrow supports center, start, end. Use a vector's correct origin; for a separate motion/direction indicator use an intentional small offset. Do not attach an external reference axis as though it is a force. Keep direction, force, and velocity meanings distinct.
- labelSide: "left" or "right" on an ARROW asks for that side of its shaft, with collision adjustment nearby.
These fields go INSIDE one diagram object on a normal DRAW command; they are not new ops. References are exact IDs on the current working page. Emit supports before attached bodies, then vectors. Updating a support/body by the same ID updates dependent geometry; retain the diagram metadata on revisions. Removed/missing/cyclic/out-of-bounds references withhold their dependent shapes rather than guessing. Current tutor item layout strings contain the original commands and constraints; an unresolved item has not been drawn. Repair that reference or remove the item. Never claim a hidden item is visible.
Syntax fragments, not a scene to copy: a circle's metadata can be "diagram":{"fill":"tint","contact":{"with":"support-id","t":0.4,"side":"left"}}. An arrow's metadata can be "diagram":{"attach":{"to":"body-id","anchor":"center"},"labelSide":"left"}. If an arrow represents a force/acceleration acting on a body, use attach to that body's center instead of a detached coordinate estimate. Keep a parallel motion indicator offset clear of the body and support, and make its from-to direction truly parallel to the path. Do not label an arrow as a force if you only mean travel direction. A reference arrow may be separate, but label it as a reference.
Use the same relationships for any subject where they apply. No canned scenes. ANIM still uses its own existing keyframe schema, not diagram metadata. If moving attachments cannot remain coherent, use a static comparison. In all diagrams, teach only the current step and leave the requested answer for the learner.
</diagram_composition>`;
